### ISSUE TITLE
assertPromiseRejectsWith is wrong

### ISSUE THREAD

**Issue by zkabic** [seregazhuk/php-react-promise-testing#22]
Hi Sergey, 
I think this method is wrong:   https://github.com/seregazhuk/php-react-promise-testing/blob/f82a634375866486fe2cbcf255634ba4867b00f5/src/AssertsPromise.php#L102

I't should look like this

```php
 /**
     * @throws AssertionFailedError
     */
    public function assertPromiseRejectsWith(PromiseInterface $promise, string $reasonExceptionClass, int $timeout = null): void
    {
        try {
            $this->waitForPromise($promise, $timeout);
        } catch (Exception $reason) {
            $this->assertInstanceOf(
                $reasonExceptionClass, $reason, 'Failed asserting that promise rejects with a specified reason.'
            );
            return;
        }

        $this->fail('Failed asserting that promise rejects. Promise was fulfilled.');
    }
```

You reject your promise with "LogicException" and that is catched here:
https://github.com/seregazhuk/php-react-promise-testing/blob/f82a634375866486fe2cbcf255634ba4867b00f5/src/AssertsPromise.php#L106

That will actually create assertion like this:

```php
$this->assertInstanceOf(\InvalidArgumentException::class, new \LogicException());
``` 

And this will not pass because InvalidArgumentException extends LogicException  but not vice versa. Trying this as new test will fail with:
```
Failed asserting that LogicException Object (...) is an instance of class "InvalidArgumentException".
```

Finally your test will catch this as  PHPUnit\Framework\ExpectationFailedException and assert this exception for valid messages and this is why your test passes.

 I think that test should look like this:

```php
/** @test */
    public function promise_rejects_with_a_specified_reason(): void
    {
        $deferred = new Deferred();
        $deferred->reject(new \InvalidArgumentException());
        $this->assertPromiseRejectsWith($deferred->promise(), \LogicException::class);
    }
```
 This should reject promise with "InvalidArgumentException" which is actually instance of "LogicException::class"

**Comment by seregazhuk** [comment]
Hi @zkabic! Thank you 👍 
Now is fixed in a new release `v0.6.1`.
