### ISSUE TITLE
v0.6.1 requires PHP >=8.0 but documentation states "Library requires PHP 7.3.0 or above"

### ISSUE THREAD

**Issue by mdissington** [seregazhuk/php-react-promise-testing#25]
Does the library really require 8.0 now?

I've been waiting for a new release that would update its dependency to phpunit 9.x (which also requires 7.3) but we don't yet support PHP 8.x so we're caught between two stools now!

**Comment by seregazhuk** [comment]
Hi @mdissington 
Yes, the readme was a bit outdated 🙈 Library was updated to PHP 8.0 and uses PHPUnit 9.^5.
