### ISSUE TITLE
How to implement with WampServer (Ratchet) ?

### ISSUE THREAD

**Issue by andreybolonin** [seregazhuk/php-react-promise-testing#7]
Hello.

Sergey, how to implement this PHPUnit assertions for ReactPHP with https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/Wamp/WampServer.php
?

Thx. :)

**Comment by seregazhuk** [comment]
Hi @andreybolonin 
Look at their tests folder https://github.com/ratchetphp/Ratchet/tree/master/tests/unit
I think you could find something useful there)

**Comment by andreybolonin** [comment]
@seregazhuk thx)
